import { $ } from "bun";
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

async function main() {
  console.log("Compiling rust to wasm32-wasip1...");
  await $`cd ../rust/wasm && cargo build --target wasm32-wasip1 --release`.nothrow();

  console.log("Running wasm-bindgen...");
  await $`wasm-bindgen ../target/wasm32-wasip1/release/iloader_wasm.wasm --out-dir wasm --target web --out-name iloader`.nothrow();

  console.log("Patching iloader.js for WASI support...");
  const jsPath = join(process.cwd(), "wasm/iloader.js");
  let jsContent = readFileSync(jsPath, "utf-8");

  // Add the window.__WASI_IMPORTS fallback injection point
  // Remove WASI snapshot imports generated by wasm-bindgen
  jsContent = jsContent.replace(
    /import \* as .* from "wasi_snapshot_preview1"\n?/g,
    "",
  );
  // Remove WASI payload from being exported by wbg_get_imports
  jsContent = jsContent.replace(
    /"wasi_snapshot_preview1": import\d+,?\n?/g,
    "",
  );

  const importRegex = /(const imports = __wbg_get_imports\(\);)/g;
  const injection = `
  if (!window.__wasi) {
      console.warn("WASI not initialized on window.__wasi, expecting LinkError");
  } else {
      imports['wasi_snapshot_preview1'] = window.__wasi.wasiImport;
  }
`;
  jsContent = jsContent.replace(importRegex, `$1${injection}`);
  writeFileSync(jsPath, jsContent);

  console.log("WASM build and patch completed successfully!");
}

main().catch(console.error);
